Import-Config-from-external-file
stefanosaittamrf/assigned-pr-counter-marfeel pull request #26
Opened 2016-12-19 01:06 UTC by dominguezcelada

2016-12-19 10:28 UTC, stefanosaittamrf commented
Code is fine. Rebase it.

2016-12-19 10:40 UTC, stefanosaittamrf requested changes
Missing the parse

2016-12-19 10:40 UTC, stefanosaittamrf commented on counting_prawns.10s.js
> +const githubConfig = require('./config.json');
You should parse the `json` in order to use it is as an object right?

2016-12-24 19:40 UTC, dominguezcelada commented on counting_prawns.10s.js
> +const githubConfig = require('./config.json');
Require of NodeJS resolved the import of a JSON file parsing its content:
https://ide.c9.io/dominguezcelada/require-nodejs-jsonfile

2016-12-25 14:36 UTC, dominguezcelada commented
By the way, once we land this change on master, we can open-spurce this. With a configuration file, this has nothing to do with Marfeel.

2017-02-22 23:19 UTC, closed without merging

2017-02-22 23:19 UTC, dominguezcelada commented
Closed until this repo gets alive again